services:
  client:
    extends:
      file: docker-compose.yaml
      service: client
    build:
      args:
        - HDS_URL=https://hdsapi.cloud.advanced.farm
        - NODE_ENV=production
    networks:
      - "hds-network"

networks:
  hds-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.103.0.1/16
