services:
  client:
    extends:
      file: docker-compose.yaml
      service: client
    build:
      args:
        - HDS_URL=https://hdsapi.cloud.advanced.farm
        - NODE_ENV=production
    networks:
      - "hds-network"
