name: Build and Test Code

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    environment:
      name: "testing"
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: install node version 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: install dependencies
        run: npm install --ignore-scripts
      - name: build frontend
        run: npm run build
      - name: test frontend
        run: npm run test
